export const SUPERVISOR_MIN_BIRTHDAY_DATE = new Date(1940, 0, 1);
export const SUPERVISOR_MIN_CITY_LENGTH = 1;
export const SUPERVISOR_MIN_CONTACT_LENGTH = 1;
export const SUPERVISOR_MIN_DESCRIPTION_LENGTH = 1;
export const SUPERVISOR_MIN_SKILLS_COUNT = 1;

export const SUPERVISOR_MAX_BIRTHDAY_DATE = new Date(2020, 0, 1);
export const SUPERVISOR_MAX_CITY_LENGTH = 20;
export const SUPERVISOR_MAX_CONTACT_LENGTH = 50;
export const SUPERVISOR_MAX_DESCRIPTION_LENGTH = 200;
export const SUPERVISOR_MAX_SKILLS_COUNT = 30;

export const SUPERVISOR_ICON_URL_DEFAULT = "/images/supervisor/default.png";
