"""Create tables

Revision ID: 3ae752c4dbe4
Revises:
Create Date: 2025-05-22 17:26:33.978040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import src

# revision identifiers, used by Alembic.
revision: str = "3ae752c4dbe4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvest2svcw",
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("st_id", sa.Uuid(), nullable=False),
        sa.Column("sv_cw_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("st_id", "sv_cw_id"),
    )
    op.create_table(
        "approvesv2stcw",
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sv_id", sa.Uuid(), nullable=False),
        sa.Column("st_cw_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("sv_id", "st_cw_id"),
    )
    op.create_table(
        "authstudent",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "authsupervisor",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=72), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "matchst2svcw",
        sa.Column("type", sa.Enum("Like", "Skip", name="matchtype"), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("st_id", sa.Uuid(), nullable=False),
        sa.Column("sv_cw_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("st_id", "sv_cw_id"),
    )
    op.create_table(
        "matchstcw2sv",
        sa.Column("type", sa.Enum("Like", "Skip", name="matchtype"), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("st_cw_id", sa.Uuid(), nullable=False),
        sa.Column("sv_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("st_cw_id", "sv_id"),
    )
    op.create_table(
        "matchsv2stcw",
        sa.Column("type", sa.Enum("Like", "Skip", name="matchtype"), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sv_id", sa.Uuid(), nullable=False),
        sa.Column("st_cw_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("sv_id", "st_cw_id"),
    )
    op.create_table(
        "matchsvcw2st",
        sa.Column("type", sa.Enum("Like", "Skip", name="matchtype"), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sv_cw_id", sa.Uuid(), nullable=False),
        sa.Column("st_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("sv_cw_id", "st_id"),
    )
    op.create_table(
        "st",
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stcw",
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stcw_student_id"), "stcw", ["student_id"], unique=False)
    op.create_table(
        "student",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "surname", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "patronymic", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "icon_url", src.shared.sql.columns.HttpUrlType(length=2083), nullable=True
        ),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "contact", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("last_online", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "studentcoursework",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "icon_url", src.shared.sql.columns.HttpUrlType(length=2083), nullable=True
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("last_change", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Approved", "Cancelled", "Matching", name="courseworkstatus"),
            nullable=False,
        ),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_studentcoursework_student_id"),
        "studentcoursework",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "supervisor",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "surname", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "patronymic", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "icon_url", src.shared.sql.columns.HttpUrlType(length=2083), nullable=True
        ),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "contact", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("last_online", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "supervisorcoursework",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "icon_url", src.shared.sql.columns.HttpUrlType(length=2083), nullable=True
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("last_change", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Approved", "Cancelled", "Matching", name="courseworkstatus"),
            nullable=False,
        ),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supervisor_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supervisorcoursework_supervisor_id"),
        "supervisorcoursework",
        ["supervisor_id"],
        unique=False,
    )
    op.create_table(
        "sv",
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "svcw",
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supervisor_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_svcw_supervisor_id"), "svcw", ["supervisor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_svcw_supervisor_id"), table_name="svcw")
    op.drop_table("svcw")
    op.drop_table("sv")
    op.drop_index(
        op.f("ix_supervisorcoursework_supervisor_id"), table_name="supervisorcoursework"
    )
    op.drop_table("supervisorcoursework")
    op.drop_table("supervisor")
    op.drop_index(
        op.f("ix_studentcoursework_student_id"), table_name="studentcoursework"
    )
    op.drop_table("studentcoursework")
    op.drop_table("student")
    op.drop_index(op.f("ix_stcw_student_id"), table_name="stcw")
    op.drop_table("stcw")
    op.drop_table("st")
    op.drop_table("matchsvcw2st")
    op.drop_table("matchsv2stcw")
    op.drop_table("matchstcw2sv")
    op.drop_table("matchst2svcw")
    op.drop_table("authsupervisor")
    op.drop_table("authstudent")
    op.drop_table("approvesv2stcw")
    op.drop_table("approvest2svcw")
    # ### end Alembic commands ###
