from datetime import date

from src.core.config import settings

STUDENT_MIN_BIRTHDAY_DATE = date(year=1940, month=1, day=1)
STUDENT_MIN_CITY_LENGTH = 1
STUDENT_MIN_CONTACT_LENGTH = 1
STUDENT_MIN_DESCRIPTION_LENGTH = 1
STUDENT_MIN_SKILLS_COUNT = 1

STUDENT_MAX_BIRTHDAY_DATE = date(year=2020, month=1, day=1)
STUDENT_MAX_CITY_LENGTH = 20
STUDENT_MAX_CONTACT_LENGTH = 50
STUDENT_MAX_DESCRIPTION_LENGTH = 200
STUDENT_MAX_SKILLS_COUNT = 30

STUDENT_ICON_URL_DEFAULT = f"{settings.FRONTEND_HOST}/images/student/default.png"
