from datetime import date

from src.core.config import settings

SUPERVISOR_MIN_BIRTHDAY_DATE = date(year=1940, month=1, day=1)
SUPERVISOR_MIN_CITY_LENGTH = 1
SUPERVISOR_MIN_CONTACT_LENGTH = 1
SUPERVISOR_MIN_DESCRIPTION_LENGTH = 1
SUPERVISOR_MIN_SKILLS_COUNT = 1

SUPERVISOR_MAX_BIRTHDAY_DATE = date(year=2020, month=1, day=1)
SUPERVISOR_MAX_CITY_LENGTH = 20
SUPERVISOR_MAX_CONTACT_LENGTH = 50
SUPERVISOR_MAX_DESCRIPTION_LENGTH = 200
SUPERVISOR_MAX_SKILLS_COUNT = 30

SUPERVISOR_ICON_URL_DEFAULT = f"{settings.FRONTEND_HOST}/images/supervisor/default.png"
