from src.core.config import settings

COURSEWORK_MIN_DESCRIPTION_LENGTH = 1
COURSEWORK_MIN_SKILLS_COUNT = 1
COURSEWORK_MIN_TITLE_LENGTH = 1

COURSEWORK_MAX_DESCRIPTION_LENGTH = 200
COURSEWORK_MAX_SKILLS_COUNT = 30
COURSEWORK_MAX_TITLE_LENGTH = 50

COURSEWORK_ICON_URL_DEFAULT = f"{settings.FRONTEND_HOST}/images/courseworks/default.png"
