export const STUDENT_MIN_BIRTHDAY_DATE = "1940-01-01";
export const STUDENT_MIN_CITY_LENGTH = 1;
export const STUDENT_MIN_CONTACT_LENGTH = 1;
export const STUDENT_MIN_DESCRIPTION_LENGTH = 1;
export const STUDENT_MIN_SKILLS_COUNT = 1;

export const STUDENT_MAX_BIRTHDAY_DATE = "2020-12-31";
export const STUDENT_MAX_CITY_LENGTH = 20;
export const STUDENT_MAX_CONTACT_LENGTH = 50;
export const STUDENT_MAX_DESCRIPTION_LENGTH = 200;
export const STUDENT_MAX_SKILLS_COUNT = 30;

export const STUDENT_ICON_URL_DEFAULT = "/images/student/default.png";
