USER_MIN_EMAIL_LENGTH = 5
USER_MIN_NAME_LENGTH = 1
USER_MIN_PASSWORD_LENGTH = 1
USER_MIN_PATRONYMIC_LENGTH = 1
USER_MIN_SURNAME_LENGTH = 1

USER_MAX_EMAIL_LENGTH = 255
USER_MAX_NAME_LENGTH = 50
USER_MAX_PASSWORD_LENGTH = 50
USER_MAX_PATRONYMIC_LENGTH = 50
USER_MAX_SURNAME_LENGTH = 50

USER_HASHED_PASSWORD_LENGTH = 72
